version: '3'

services:

  web:
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
    #  - VIRTUAL_HOST=mattstrong.com,www.mattstrong.com
    #  - LETSENCRYPT_HOST=mattstrong.com,www.mattstrong.com
    #  - LETSENCRYPT_EMAIL=matt@mattstrong.com
    networks:
      - vps-config_proxy-tier

networks:
  vps-config_proxy-tier:
    external: true
