version: '3'

services:
    web:
        build:
            context: .
            args:
                baseurl: mattstrong.com
        restart: always
        environment:
            - VIRTUAL_HOST=mattstrong.com,www.mattstrong.com
            - LETSENCRYPT_HOST=mattstrong.com,www.mattstrong.com
            - LETSENCRYPT_EMAIL=matt@mattstrong.com
            # - VIRTUAL_HOST=localhost
        networks:
            - vps-config_proxy-tier

networks:
    vps-config_proxy-tier:
        external: true
