# Page settings

baseURL = "https://mattstrong.com/resume/"
languageCode = "en-us"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Matthew Strong"
    description = "My Resume"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Matthew Strong"
        tagline = "Software Engineer"
        avatar = "me.png"

    [params.contact]
        enable = true
        location = "Milwaukee, WI"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:14142125677"
        text = "1.414.212.5677"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:matt@mattstrong.com"
        text = "matt@mattstrong.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://mattstrong.com"
        text = "www.mattstrong.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Programming Languages"
        [[params.skills.list.items]]
        details = "C++, Python, Bash (10 yrs)"
        [[params.skills.list.items]]
        details = "Javascript, HTML/CSS (5 yrs)"
        [[params.skills.list.items]]
        details = "Java (3 yrs)"

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Modern C++ design / STL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Software benchmarking and optimization"
        [[params.skills.list.items]]
        details = "Linux kernel debugging"
        [[params.skills.list.items]]
        details = "C++ microservice design"

        [[params.skills.list.items]]
        details = "Unit and component test frameworks"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong technical problem solver"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Effective communicator"
        [[params.skills.list.items]]
        details = "Working with and leading agile teams"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc Computer Engineering"
        university = "Marquette University"
        honors = "magna cum laude"
        dates = "2005 - 2010"

    [params.awards]
        enable = false

    [params.certifications]
        enable = true

        [[params.certifications.list]]
        name = "Neural Networks and Deep Learning"
        body = "deeplearning.ai"
        date = "2019"
        [[params.certifications.list]]
        name = "Linux Kernel Driver Development"
        body = "Dualos"
        date = "2019"

    [params.languages]
        enable = false

    [params.interests]
        enable = false

    [params.summary]
        enable = true
        text = """I am an experienced and highly motivated software engineer with over 10 years of hands on experience creating and implementing software designs and leading advanced technology projects. I have a passion for modern software design practices and working with cutting edge technologies. I have wide ranging experiences in product design, working closely with customers, systems engineers, researchers, and developers to produce many innovative and life-saving products in the healthcare industry."""

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Staff Software Engineer,"
        dates = "2019 - 2020"
        company = "XRay Engineering | GE Healthcare"
        title_alt = "Senior Software Engineer"
        dates_alt = "2016 - 2019"
        details = """Software developer and team lead working on new product development for fixed and mobile xray products. I lead a wide array of initiatives across software subsystems, focused on integrating new xray detector technologies and improving software quality and reliability, as well as evaluating new technologies in AI and computer vision."""

        [[params.experience.list.items]]
        details = "Collaborated with third-party detector vendors for integrating their SDKs into xray products. Implemented a detector abstraction API based on ZMQ communication framework to facilitate quicker integration of additional detectors and improve reliability."
        [[params.experience.list.items]]
        details = "Redesigned the product network architecture using network namespaces and layer 2 hardware / 802.1Q VLAN tagging. Developed device monitoring software using SNMP to remotely sense physical connect/disconnect of xray detectors."
        [[params.experience.list.items]]
        details = "Developed prototypes for first on-device artificial intelligence algorithm for detecting Pneumothorax in patient images. Worked closely with data scientists to benchmark and optimize model performance."
        [[params.experience.list.items]]
        details = "Lead a computer vision ATD project to improve patient positioning and protocol selection by using depth cameras to estimate patient size and position. Developed a video streaming platform based on gstreamer and WebRTC protocols that is used across GEHC for integrating computer vision algorithms into live streaming applications. "

        [[params.experience.list]]
        title = "Lead Software Engineer,"
        dates = "2014 - 2016"
        company = "PET/CT Engineering | GE Healthcare"
        title_alt = "Software Engineer"
        dates_alt = "2011 - 2014"
        details = """Software engineer focused on image acquisition and reconstruction software development for Position Emission Tomography scanners.   In this role, I gained experience in C++ design and Linux development, and developed a passion for high performance computing and software performance optimization."""

        [[params.experience.list.items]]
        details = "Lead the development of a new data acquisition and reconstruction compute platform by evaluating new technologies for improving data throughput, including multi-CPU architectures, discrete GPUs, and SSDs. Achieved a 40% data throughput increase capable of performing TOF List mode acquisitions of up to 21 million events per second."
        [[params.experience.list.items]]
        details = "Implemented the manual calibration and iterative CTC calibration algorithms for BGO PET detectors, and worked closely with systems scientists to evaluate accuracy and performance of the implementations."
        [[params.experience.list.items]]
        details = "Worked directly with support engineers to diagnose software and hardware failures in the field, and to develop new diagnostic software for monitoring and predicting hardware failures."
        [[params.experience.list.items]]
        details = "Collaborated with global research team to productize the first ever device-less respiratory gating algorithm. Converted and optimized the MATLAB PCA algorithm into C++ and integrated processing into the PET coincidence stream. "
        [[params.experience.list.items]]
        details = "Developed a vendor independant file format for PET sinogram and list data based on HDF5 that is used by scientists and researchers. Implemented using HDF5, it incorporates GE proprietary algorithms to transparently compress and decompress data."

        [[params.experience.list]]
        title = "Early Identification Co-op Program"
        dates = "2007 - 2009"
        company = "GE Healthcare"
        details = "Participant in the GEHC Early Identification (EID) program, where I completed 4 semester long rotations in different healthcare engineering modalities, including Computed Tomography, Patient Monitoring, and technology tools teams. Upon program graduation, I received the W. D. Bliss Outstanding Co-op Award for my contributions."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "HDF5 (Hierarchical Data Format)"
        meta = "Open Source"
        tagline = "Implemented the direct chunk read API in the HDF5 open source project, which enables performance critical applications to perform data decompression and filtering independent of the HDF5 API."
        [[params.projects.list.items]]
        details = "Etiam ultricies nisi vel augue."

    [params.information]
        enable = false

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/strong-matthew"
        title = "strong-matthew"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/matthewstrong"
        title = "matthewstrong"
